name: hrms_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Adjusted SDK range for compatibility

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9
  sqflite: ^2.3.0
  firebase_core: ^3.6.0 # Updated to latest stable version
  firebase_auth: ^5.3.1 # Updated to latest stable version
  cloud_firestore: ^5.4.4 # Updated to latest stable version
  firebase_storage: ^12.3.2 # Updated to latest stable version
  firebase_storage_web: ^3.9.1 # Updated to latest stable version
  slide_to_act: ^2.0.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0 # Downgraded to stable version compatible with SDK
  pdf: ^3.11.0
  printing: ^5.13.1
  file_picker: ^10.2.0
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  csv: ^6.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Updated to latest stable version

flutter:
  uses-material-design: true

  assets:
    - assets/profile/