// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8XuuQPgX7x-nVSCtKRKi_8qdljQEjsd8',
    appId: '1:392396373530:web:9393f04c4a03fc83329ba3',
    messagingSenderId: '392396373530',
    projectId: 'hrmsprojects-9577b',
    authDomain: 'hrmsprojects-9577b.firebaseapp.com',
    storageBucket: 'hrmsprojects-9577b.firebasestorage.app',
    measurementId: 'G-ZK0RDTBT7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWbypzsqsfFS4bHXy1kJ254J2upm_twSI',
    appId: '1:392396373530:android:2b1580cbdd941105329ba3',
    messagingSenderId: '392396373530',
    projectId: 'hrmsprojects-9577b',
    storageBucket: 'hrmsprojects-9577b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkRnkma61IL8-p96MJpt7skNL-BoIGmEE',
    appId: '1:392396373530:ios:549011053097b6dd329ba3',
    messagingSenderId: '392396373530',
    projectId: 'hrmsprojects-9577b',
    storageBucket: 'hrmsprojects-9577b.firebasestorage.app',
    iosBundleId: 'com.example.hrmsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkRnkma61IL8-p96MJpt7skNL-BoIGmEE',
    appId: '1:392396373530:ios:549011053097b6dd329ba3',
    messagingSenderId: '392396373530',
    projectId: 'hrmsprojects-9577b',
    storageBucket: 'hrmsprojects-9577b.firebasestorage.app',
    iosBundleId: 'com.example.hrmsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8XuuQPgX7x-nVSCtKRKi_8qdljQEjsd8',
    appId: '1:392396373530:web:fe9a99358708229a329ba3',
    messagingSenderId: '392396373530',
    projectId: 'hrmsprojects-9577b',
    authDomain: 'hrmsprojects-9577b.firebaseapp.com',
    storageBucket: 'hrmsprojects-9577b.firebasestorage.app',
    measurementId: 'G-4R5RX7YCCD',
  );

}