// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkE3VNLIKLvzckY7zGuruSTkvlslSdiEA',
    appId: '1:733410798323:web:26f97d56354976859de586',
    messagingSenderId: '733410798323',
    projectId: 'hrmsdb-91697',
    authDomain: 'hrmsdb-91697.firebaseapp.com',
    storageBucket: 'hrmsdb-91697.firebasestorage.app',
    measurementId: 'G-8W9RM7P116',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqux8T1_FZVIL6G4ZajhSP23ztNURBX78',
    appId: '1:733410798323:android:3e4dfac9a0b946e79de586',
    messagingSenderId: '733410798323',
    projectId: 'hrmsdb-91697',
    storageBucket: 'hrmsdb-91697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrDWDcBACAaGdbRKwKxNLaaPCGe3ACBiA',
    appId: '1:733410798323:ios:974571145d96fff49de586',
    messagingSenderId: '733410798323',
    projectId: 'hrmsdb-91697',
    storageBucket: 'hrmsdb-91697.firebasestorage.app',
    iosBundleId: 'com.example.hrmsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrDWDcBACAaGdbRKwKxNLaaPCGe3ACBiA',
    appId: '1:733410798323:ios:974571145d96fff49de586',
    messagingSenderId: '733410798323',
    projectId: 'hrmsdb-91697',
    storageBucket: 'hrmsdb-91697.firebasestorage.app',
    iosBundleId: 'com.example.hrmsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkE3VNLIKLvzckY7zGuruSTkvlslSdiEA',
    appId: '1:733410798323:web:1576ffb956158ab19de586',
    messagingSenderId: '733410798323',
    projectId: 'hrmsdb-91697',
    authDomain: 'hrmsdb-91697.firebaseapp.com',
    storageBucket: 'hrmsdb-91697.firebasestorage.app',
    measurementId: 'G-XB1XXWFWYV',
  );

}